# Generated by Django 5.1.6 on 2025-03-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='description',
        ),
    ]
